### ISSUE TITLE
ModuleNotFoundError for 'tfold_se3.from_se3cnn'

### ISSUE THREAD

**Issue by stau-7001** [yuzhiguo07/Protein-Structure-Embedding#2]
Hello,
I encountered a ModuleNotFoundError while trying to run the build_dataset_sample.py script in the project.
Here's the error message I received:

python build_dataset_sample.py
Using backend: pytorch
Traceback (most recent call last):
  File "build_dataset_sample.py", line 14, in <module>
    from tfold_se3.utils import tfold_init
  File "/userhome/aimia/lyt/Protein-Structure-Embedding/tfold_se3/utils/__init__.py", line 28, in <module>
    from tfold_se3.utils.se3_utils import get_basis_and_radial
  File "/userhome/aimia/lyt/Protein-Structure-Embedding/tfold_se3/utils/se3_utils.py", line 9, in <module>
    from tfold_se3.from_se3cnn import utils_steerable
ModuleNotFoundError: No module named 'tfold_se3.from_se3cnn'

It seems that there might be an issue with the project structure or a missing file. Could you please help me resolve this issue? Any guidance on how to fix this problem would be greatly appreciated.

Thank you.

**Comment by yuzhiguo07** [comment]
The 'tfold_se3.from_se3cnn' is used in another project, and it will not be used in this case; I just commented out this. You can comment out all 'import packages' if they are missing.  btw, you may modify the 'build_dataset' because of #1 . The goal of 'build_dataset' is to generate hdf5.files and please check the data format in [pdb/task01/hdf5.files ](https://github.com/yuzhiguo07/Protein-Structure-Embedding/tree/main/pdb/task01/hdf5.files) for a reference.
